In [1]:
import pandas as pd
import pickle
import time
from scholarly import scholarly

In [2]:
DATA_FOLDER = '../../data/'

In [7]:
with open(f'{DATA_FOLDER}authors.pickle', 'rb') as handle:
    authors = pickle.load(handle)

In [8]:
import spacy

# Load the spaCy language model
nlp = spacy.load("en_core_web_sm")

def extract_organizations(affiliation):
    """Extracts organization names from a affiliation value of an author record."""
    organizations = []
    
    doc = nlp(affiliation)
    # Extract entities labeled as ORG (organization)
    for ent in doc.ents:
        if ent.label_ == "ORG":
            organizations.append(ent.text)
    return organizations

In [9]:
def generate_organizations(authors):
    author_organizations_df = pd.DataFrame()
    data = list()
    
    for author in authors:
        affiliation = author['affiliation']
        author_id = author['author_id']
        if affiliation != 'Unknown':            
            try:                
                print(f'Extracting organizations for author with id {author_id}...')
                organizations = extract_organizations(affiliation)
                for org in organizations:
                    data.append((author_id, org))                                
            except Exception as e:
                print(f"Error processing author with id {author_id}: {e}")
                
    author_organizations_df = pd.DataFrame(data, columns=["author_id", "organization"])
    return author_organizations_df

# Extract and store organizations from the author-affiliation field

In [10]:
author_organizations_df = generate_organizations(authors)

Extracting organizations for author with id zkBXb_kAAAAJ...
Extracting organizations for author with id EHvA-IUAAAAJ...
Extracting organizations for author with id 5RoxYhkAAAAJ...
Extracting organizations for author with id ap3FfWEAAAAJ...
Extracting organizations for author with id uxiJL_cAAAAJ...
Extracting organizations for author with id QV_7inYAAAAJ...
Extracting organizations for author with id JNrJo8cAAAAJ...
Extracting organizations for author with id o70NT8IAAAAJ...
Extracting organizations for author with id ZeGca3cAAAAJ...
Extracting organizations for author with id o3DdNZMAAAAJ...
Extracting organizations for author with id Ydo9ResAAAAJ...
Extracting organizations for author with id 4IRe3WYAAAAJ...
Extracting organizations for author with id eKtUwa4AAAAJ...
Extracting organizations for author with id dYi-SW8AAAAJ...
Extracting organizations for author with id -Hz8RP0AAAAJ...
Extracting organizations for author with id t-hrVHwAAAAJ...
Extracting organizations for author with id AQw0V9oAAAAJ...
Extracting organizations for author with id SOXSCmYAAAAJ...
Extracting organizations for author with id k0m8X_AAAAAJ...
Extracting organizations for author with id Lcmc_iUAAAAJ...
Extracting organizations for author with id WfzNXGIAAAAJ...
Extracting organizations for author with id CAqOVLoAAAAJ...
Extracting organizations for author with id WI2DzroAAAAJ...
Extracting organizations for author with id _cd4obcAAAAJ...
Extracting organizations for author with id p0RpE8gAAAAJ...
Extracting organizations for author with id koO4f-oAAAAJ...
Extracting organizations for author with id W4ewWf0AAAAJ...
Extracting organizations for author with id Q6b80i8AAAAJ...
Extracting organizations for author with id wicacBwAAAAJ...
Extracting organizations for author with id kERS9vUAAAAJ...
Extracting organizations for author with id O_xxMoQAAAAJ...
Extracting organizations for author with id 1ID1p54AAAAJ...
Extracting organizations for author with id BOUG-tsAAAAJ...
Extracting organizations for author with id hOr2nV0AAAAJ...
Extracting organizations for author with id QNtOrigAAAAJ...
Extracting organizations for author with id OdLQTz4AAAAJ...
Extracting organizations for author with id mQUusK0AAAAJ...
Extracting organizations for author with id Bphl_fIAAAAJ...
Extracting organizations for author with id jH9HWzMAAAAJ...
Extracting organizations for author with id ZQRR-C4AAAAJ...
Extracting organizations for author with id kae35NwAAAAJ...
Extracting organizations for author with id CJpcEFcAAAAJ...
Extracting organizations for author with id b0OGQV0AAAAJ...
Extracting organizations for author with id I--l0IsAAAAJ...
Extracting organizations for author with id Zlb-qX4AAAAJ...
Extracting organizations for author with id JNPsgrQAAAAJ...
Extracting organizations for author with id nZH_Ws8AAAAJ...
Extracting organizations for author with id _nA7UxUAAAAJ...
Extracting organizations for author with id DN4kew8AAAAJ...
Extracting organizations for author with id FadEO7wAAAAJ...
Extracting organizations for author with id xAqx-WkAAAAJ...
Extracting organizations for author with id 2tbe1RoAAAAJ...
Extracting organizations for author with id Vt5edEkAAAAJ...
Extracting organizations for author with id ZTMJkLEAAAAJ...
Extracting organizations for author with id 9RnYXQEAAAAJ...
Extracting organizations for author with id 9130GfwAAAAJ...
Extracting organizations for author with id MXTKwBYAAAAJ...
Extracting organizations for author with id 9Lh2DnAAAAAJ...
Extracting organizations for author with id 9qDSSJwAAAAJ...
Extracting organizations for author with id jVn0wDMAAAAJ...
Extracting organizations for author with id Bew0NN8AAAAJ...
Extracting organizations for author with id Vu5h_KAAAAAJ...
Extracting organizations for author with id ysfbgQsAAAAJ...
Extracting organizations for author with id t1ouXTMAAAAJ...
Extracting organizations for author with id B6LqguIAAAAJ...
Extracting organizations for author with id I79wP4sAAAAJ...
Extracting organizations for author with id bf3roVQAAAAJ...
Extracting organizations for author with id xikbGv0AAAAJ...
Extracting organizations for author with id 7IAXeUwAAAAJ...
Extracting organizations for author with id PENhrsoAAAAJ...
Extracting organizations for author with id -o3I0zUAAAAJ...
Extracting organizations for author with id J9cZWe0AAAAJ...
Extracting organizations for author with id eYj7cAUAAAAJ...
Extracting organizations for author with id UU8C8SsAAAAJ...
Extracting organizations for author with id JpEBjrsAAAAJ...
Extracting organizations for author with id BHrQQJUAAAAJ...
Extracting organizations for author with id OpnEnXsAAAAJ...
Extracting organizations for author with id MwmeyN8AAAAJ...
Extracting organizations for author with id R3xGI_8AAAAJ...
Extracting organizations for author with id spwpSeMAAAAJ...
Extracting organizations for author with id bg4UgQ0AAAAJ...
Extracting organizations for author with id wtEjU0cAAAAJ...
Extracting organizations for author with id 4m3GPFYAAAAJ...
Extracting organizations for author with id 8TfWi0EAAAAJ...
Extracting organizations for author with id Z8fcElsAAAAJ...
Extracting organizations for author with id jdr7n5wAAAAJ...
Extracting organizations for author with id A_eC8r0AAAAJ...
Extracting organizations for author with id kfbc33sAAAAJ...
Extracting organizations for author with id BCVDCHcAAAAJ...
Extracting organizations for author with id UedS9LQAAAAJ...
Extracting organizations for author with id AWfIieMAAAAJ...
Extracting organizations for author with id 6p8aoG0AAAAJ...
Extracting organizations for author with id 1rLPRzIAAAAJ...
Extracting organizations for author with id WdtK7WsAAAAJ...
Extracting organizations for author with id ddJb53YAAAAJ...
Extracting organizations for author with id pu5CdXoAAAAJ...
Extracting organizations for author with id MeSogXgAAAAJ...
Extracting organizations for author with id 7PVmb8MAAAAJ...
Extracting organizations for author with id cdre5G0AAAAJ...
Extracting organizations for author with id 1wloHDIAAAAJ...
Extracting organizations for author with id Tc_U_9YAAAAJ...
Extracting organizations for author with id 74bs5g8AAAAJ...
Extracting organizations for author with id ACdb-8YAAAAJ...
Extracting organizations for author with id dlapiW8AAAAJ...
Extracting organizations for author with id jV50Ks8AAAAJ...
Extracting organizations for author with id clJGV9UAAAAJ...
Extracting organizations for author with id AEaAOCQAAAAJ...
Extracting organizations for author with id QVJvfz8AAAAJ...
Extracting organizations for author with id BP702PgAAAAJ...

In [11]:
author_organizations_df

        author_id                           organization
0    zkBXb_kAAAAJ                 Biomedical Informatics
1    zkBXb_kAAAAJ                    Shandong University
2    EHvA-IUAAAAJ                     Tianjin University
3    EHvA-IUAAAAJ                    Tsinghua University
4    EHvA-IUAAAAJ           City University of Hong Kong
..            ...                                    ...
111  1wloHDIAAAAJ           City University of Hong Kong
112  Tc_U_9YAAAAJ                             Amazon.com
113  jV50Ks8AAAAJ  Biostatistics, University of Michigan
114  QVJvfz8AAAAJ        Computer Science and Engineeing
115  BP702PgAAAAJ                      Monash University

[116 rows x 2 columns]

In [19]:
author_organizations_df.to_parquet(f'{DATA_FOLDER}author_organizations.parquet')

In [24]:
organizations_df = pd.DataFrame(author_organizations_df['organization'].unique(), columns=['organization'])

In [25]:
organizations_df

                              organization
0                   Biomedical Informatics
1                      Shandong University
2                       Tianjin University
3                      Tsinghua University
4             City University of Hong Kong
..                                     ...
105                         Data Scientist
106                             Amazon.com
107  Biostatistics, University of Michigan
108        Computer Science and Engineeing
109                      Monash University

[110 rows x 1 columns]

In [26]:
organizations_df.to_parquet(f'{DATA_FOLDER}organizations.parquet')